[project]
name = "native_sparse_attention"
dynamic = ["version"]
description = "Trtion kernels for Native Sparse Attention"
readme = "README.md"
authors = [
    { name = "Songlin Yang", email = "yangsl66@mit.edu" },
    { name = "Yu Zhang", email = "yzhang.cs@outlook.com" },
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.10"
dependencies = [
    "triton>=3.0",
    "datasets>=3.3.0",
    "einops",
    "ninja",
]

[project.optional-dependencies]
conv1d = ["causal-conv1d>=1.4.0"]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/fla-org/native-sparse-attention"

[build-system]
requires = ["setuptools>=45", "wheel", "ninja"]
build-backend = "setuptools.build_meta"

[tool.isort]
line_length = 127
multi_line_output = 3